# Generated by Django 3.0.8 on 2020-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waterfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255, verbose_name='名称')),
                ('img_url', models.CharField(max_length=1024)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('style', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '图片瀑布',
                'db_table': 'Waterfall_image',
            },
        ),
    ]
