# Generated by Django 3.0.8 on 2020-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterfall', '0003_auto_20200722_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='img_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
